name: project/frontend/yaml
inputs:
- name: enableDocker
  label: Do you want to add a Dockerfile for your React application
  bool: {}
tools:
- name: nodejs
  displayTitle: Node.js
  tests:
  - cmd: node
    args:
      - '-v'
recipes:
- recipe: docker/react
  include: '{{ .inputs.enableDocker }}'
  inputs:
  - name: root
    # Set to the cwd as the react root is created by this recipe
    value: "."
  - name: createNginxConfig
    # Set to true, as there can not be an existing NGINX config
    value: true
steps:
- label: Create react app
  tool:
    name: node
    cmd: npx
    args:
    - create-react-app
    - "."
    - "--template"
    - typescript